-- Postgres schema for the ticket manager, mirroring the SQLite schema in
-- lib/db.js. Applied by scripts/migrate-sqlite-to-neon.mjs.
--
-- Differences from the SQLite original, and why:
--   * INTEGER PRIMARY KEY AUTOINCREMENT -> GENERATED BY DEFAULT AS IDENTITY.
--     BY DEFAULT (not ALWAYS) so the migration can insert explicit ids.
--   * TEXT timestamps -> timestamptz. SQLite stored these as UTC strings from
--     datetime('now'); the migration runs with the session set to UTC so the
--     values keep their original instant.
--   * employees.active stays an integer rather than a boolean, because the
--     application layer writes `active ? 1 : 0`.
--   * sessions.expires_at is epoch milliseconds (Date.now() + TTL), so bigint.
--   * email_outbox is created after tickets, because it references tickets(id).
--     SQLite allowed the forward reference; Postgres resolves it at creation.

CREATE TABLE IF NOT EXISTS users (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text        NOT NULL,
  email      text        NOT NULL UNIQUE,
  password   text        NOT NULL,
  role       text        NOT NULL CHECK (role IN ('admin', 'developer', 'client')),
  must_change_password integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS workspaces (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key         text        NOT NULL UNIQUE,
  name        text        NOT NULL,
  description text        NOT NULL DEFAULT '',
  color       text        NOT NULL DEFAULT '#0c66e4',
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS projects (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key          text        NOT NULL UNIQUE,
  name         text        NOT NULL,
  description  text        NOT NULL DEFAULT '',
  color        text        NOT NULL DEFAULT '#0c66e4',
  workspace_id integer              REFERENCES workspaces (id),
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS employees (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text        NOT NULL,
  email       text        NOT NULL UNIQUE,
  role        text        NOT NULL DEFAULT 'developer' CHECK (role IN ('admin', 'developer', 'client')),
  department  text        NOT NULL DEFAULT '',
  title       text        NOT NULL DEFAULT '',
  active      integer     NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tickets (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       text        NOT NULL,
  description text        NOT NULL,
  status      text        NOT NULL DEFAULT 'open'
              CHECK (status IN ('open', 'in_progress', 'resolved', 'closed')),
  priority    text        NOT NULL DEFAULT 'medium'
              CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
  type        text        NOT NULL DEFAULT 'task'
              CHECK (type IN ('task', 'bug', 'story', 'epic')),
  created_by  integer     NOT NULL REFERENCES users (id),
  assigned_to integer              REFERENCES users (id),
  project_id  integer              REFERENCES projects (id),
  employee_id integer              REFERENCES employees (id),
  labels      text        NOT NULL DEFAULT '',
  due_date    text,
  start_date  text,
  category    text        NOT NULL DEFAULT '',
  team        text        NOT NULL DEFAULT '',
  budget      real        NOT NULL DEFAULT 0,
  estimate_seconds integer NOT NULL DEFAULT 0,
  parent_id   integer              REFERENCES tickets (id),
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS email_outbox (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  to_email   text        NOT NULL,
  to_name    text        NOT NULL DEFAULT '',
  subject    text        NOT NULL,
  body_text  text        NOT NULL,
  body_html  text        NOT NULL DEFAULT '',
  trigger    text        NOT NULL DEFAULT 'assignment',
  ticket_id  integer              REFERENCES tickets (id),
  status     text        NOT NULL DEFAULT 'sent' CHECK (status IN ('sent', 'logged', 'failed')),
  error      text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sessions (
  token      text PRIMARY KEY,
  user_id    integer     NOT NULL REFERENCES users (id),
  expires_at bigint      NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ticket_activity (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id  integer     NOT NULL REFERENCES tickets (id),
  actor_id   integer              REFERENCES users (id),
  field      text        NOT NULL,
  from_value text        NOT NULL DEFAULT '',
  to_value   text        NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ticket_comments (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id  integer     NOT NULL REFERENCES tickets (id),
  author_id  integer     NOT NULL REFERENCES users (id),
  body       text        NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ticket_attachments (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id    integer     NOT NULL REFERENCES tickets (id),
  filename     text        NOT NULL,
  storage_key  text        NOT NULL,
  content_type text        NOT NULL DEFAULT '',
  size_bytes   integer     NOT NULL DEFAULT 0,
  uploaded_by  integer              REFERENCES users (id),
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ticket_relations (
  id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id         integer     NOT NULL REFERENCES tickets (id),
  related_ticket_id integer     NOT NULL REFERENCES tickets (id),
  relation_type     text        NOT NULL DEFAULT 'relates_to'
                    CHECK (relation_type IN ('parent_of', 'child_of', 'blocks', 'blocked_by',
                                            'relates_to', 'duplicates', 'duplicated_by',
                                            'clones', 'cloned_by')),
  created_at        timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ticket_watchers (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id  integer     NOT NULL REFERENCES tickets (id),
  user_id    integer     NOT NULL REFERENCES users (id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ticket_time_logs (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id  integer     NOT NULL REFERENCES tickets (id),
  user_id    integer     NOT NULL REFERENCES users (id),
  seconds    integer     NOT NULL DEFAULT 0,
  note       text        NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ticket_votes (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id  integer     NOT NULL REFERENCES tickets (id),
  user_id    integer     NOT NULL REFERENCES users (id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ticket_web_links (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id  integer     NOT NULL REFERENCES tickets (id),
  url        text        NOT NULL,
  label      text        NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS happy_sheet_submissions (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submitted_by    integer REFERENCES users (id),
  name            text    NOT NULL,
  happy_one       text    NOT NULL,
  happy_others    text    NOT NULL DEFAULT '',
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS task_sheet_submissions (
  id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submitted_by       integer REFERENCES users (id),
  name               text    NOT NULL,
  project            text    NOT NULL,
  hours_worked       double precision NOT NULL,
  task_title         text    NOT NULL,
  task_description   text    NOT NULL,
  task_state         text    NOT NULL
                     CHECK (task_state IN ('completed', 'not_completed')),
  -- Only filled when the state is not_completed: what stopped the work.
  blocker            text,
  linked_ticket_id   integer REFERENCES tickets (id),
  created_at         timestamptz NOT NULL DEFAULT now()
);

-- Matches the indexes the application relies on for list and filter queries.
CREATE INDEX IF NOT EXISTS tickets_status_idx    ON tickets (status);
CREATE INDEX IF NOT EXISTS tickets_project_idx  ON tickets (project_id);
CREATE INDEX IF NOT EXISTS tickets_employee_idx ON tickets (employee_id);
CREATE INDEX IF NOT EXISTS tickets_assignee_idx ON tickets (assigned_to);
CREATE INDEX IF NOT EXISTS employees_active_idx  ON employees (active);
CREATE INDEX IF NOT EXISTS sessions_user_idx    ON sessions (user_id);
CREATE INDEX IF NOT EXISTS outbox_ticket_idx   ON email_outbox (ticket_id);
CREATE INDEX IF NOT EXISTS activity_ticket_idx  ON ticket_activity (ticket_id);
CREATE INDEX IF NOT EXISTS comments_ticket_idx  ON ticket_comments (ticket_id);
CREATE INDEX IF NOT EXISTS attachments_ticket_idx ON ticket_attachments (ticket_id);
CREATE INDEX IF NOT EXISTS relations_ticket_idx ON ticket_relations (ticket_id);
CREATE INDEX IF NOT EXISTS watchers_ticket_idx ON ticket_watchers (ticket_id);
CREATE INDEX IF NOT EXISTS timelogs_ticket_idx ON ticket_time_logs (ticket_id);
CREATE INDEX IF NOT EXISTS votes_ticket_idx    ON ticket_votes (ticket_id);
CREATE INDEX IF NOT EXISTS weblinks_ticket_idx ON ticket_web_links (ticket_id);
CREATE INDEX IF NOT EXISTS task_sheet_created_idx ON task_sheet_submissions (created_at);
CREATE INDEX IF NOT EXISTS task_sheet_name_idx    ON task_sheet_submissions (name);
CREATE INDEX IF NOT EXISTS happy_sheet_created_idx ON happy_sheet_submissions (created_at);
CREATE INDEX IF NOT EXISTS happy_sheet_name_idx    ON happy_sheet_submissions (name);

-- Additive changes. CREATE TABLE IF NOT EXISTS leaves an existing table alone,
-- so a column introduced after a database was first migrated has to be added
-- explicitly. Each block checks information_schema first, which keeps the whole
-- script safe to re-run.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'projects' AND column_name = 'workspace_id'
  ) THEN
    ALTER TABLE projects ADD COLUMN workspace_id integer REFERENCES workspaces (id);
  END IF;
END
$$;

-- An admin-created account gets a temporary password that has to be changed at
-- first login, so the flag that enforces it is added to databases that predate
-- it. 0/1 rather than a boolean, matching the rest of the schema.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'users' AND column_name = 'must_change_password'
  ) THEN
    ALTER TABLE users ADD COLUMN must_change_password integer NOT NULL DEFAULT 0;
  END IF;
END
$$;

-- The index is created after the column, not alongside the other indexes, so an
-- already-migrated database can add the column first and index it second.
CREATE INDEX IF NOT EXISTS projects_workspace_idx ON projects (workspace_id);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'tickets' AND column_name = 'type'
  ) THEN
    ALTER TABLE tickets ADD COLUMN type text NOT NULL DEFAULT 'task'
      CHECK (type IN ('task', 'bug', 'story', 'epic'));
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'tickets' AND column_name = 'labels'
  ) THEN
    ALTER TABLE tickets ADD COLUMN labels text NOT NULL DEFAULT '';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'tickets' AND column_name = 'due_date'
  ) THEN
    ALTER TABLE tickets ADD COLUMN due_date text;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'tickets' AND column_name = 'start_date'
  ) THEN
    ALTER TABLE tickets ADD COLUMN start_date text;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'tickets' AND column_name = 'category'
  ) THEN
    ALTER TABLE tickets ADD COLUMN category text NOT NULL DEFAULT '';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'tickets' AND column_name = 'team'
  ) THEN
    ALTER TABLE tickets ADD COLUMN team text NOT NULL DEFAULT '';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'tickets' AND column_name = 'budget'
  ) THEN
    ALTER TABLE tickets ADD COLUMN budget real NOT NULL DEFAULT 0;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'tickets' AND column_name = 'estimate_seconds'
  ) THEN
    ALTER TABLE tickets ADD COLUMN estimate_seconds integer NOT NULL DEFAULT 0;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'tickets' AND column_name = 'parent_id'
  ) THEN
    ALTER TABLE tickets ADD COLUMN parent_id integer REFERENCES tickets (id);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'tickets' AND column_name = 'archived'
  ) THEN
    ALTER TABLE tickets ADD COLUMN archived integer NOT NULL DEFAULT 0;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'tickets' AND column_name = 'archived_at'
  ) THEN
    ALTER TABLE tickets ADD COLUMN archived_at text;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'tickets' AND column_name = 'slack_channel'
  ) THEN
    ALTER TABLE tickets ADD COLUMN slack_channel text NOT NULL DEFAULT '';
  END IF;
END
$$;

-- The blocker answer arrived after the sheet itself. Nullable, so no default
-- is needed and rows filed before it remain valid.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'task_sheet_submissions'
      AND column_name = 'blocker'
  ) THEN
    ALTER TABLE task_sheet_submissions ADD COLUMN blocker text;
  END IF;
END
$$;

-- Only now is parent_id guaranteed to exist, so the index has to be created
-- here rather than alongside the bootstrap indexes: on a database that
-- predates the column, Postgres would fail the whole script with
-- 'column "parent_id" does not exist'. Same reasoning for archived.
CREATE INDEX IF NOT EXISTS tickets_parent_idx ON tickets (parent_id);
CREATE INDEX IF NOT EXISTS tickets_archived_idx ON tickets (archived);

-- Existing databases carry the original relation_type CHECK, which has no room
-- for the parenting or clone types. Drop it and put the current list back.
-- Guarded on 'clones' rather than 'parent_of' because that is the newest type:
-- a database already carrying the parenting types still needs this pass, and
-- testing for the newer value catches both cases.
DO
$$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'ticket_relations_relation_type_check'
  ) AND NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'ticket_relations_relation_type_check'
      AND pg_get_constraintdef(oid) LIKE '%clones%'
  ) THEN
    ALTER TABLE ticket_relations DROP CONSTRAINT ticket_relations_relation_type_check;
    ALTER TABLE ticket_relations
      ADD CONSTRAINT ticket_relations_relation_type_check
      CHECK (relation_type IN ('parent_of', 'child_of', 'blocks', 'blocked_by',
                               'relates_to', 'duplicates', 'duplicated_by',
                               'clones', 'cloned_by'));
  END IF;
END
$$;

-- Parenting used to be stored as a parent_of row. Move any that exist onto
-- tickets.parent_id and delete the rows, so a ticket's place in the hierarchy
-- lives in exactly one place. child_of rows carry the same information in the
-- other direction and are folded in with the columns swapped.
UPDATE tickets
SET parent_id = (
  SELECT r.ticket_id FROM ticket_relations r
  WHERE r.relation_type = 'parent_of' AND r.related_ticket_id = tickets.id
  ORDER BY r.id LIMIT 1
)
WHERE parent_id IS NULL AND EXISTS (
  SELECT 1 FROM ticket_relations r
  WHERE r.relation_type = 'parent_of' AND r.related_ticket_id = tickets.id
);

UPDATE tickets
SET parent_id = (
  SELECT r.related_ticket_id FROM ticket_relations r
  WHERE r.relation_type = 'child_of' AND r.ticket_id = tickets.id
  ORDER BY r.id LIMIT 1
)
WHERE parent_id IS NULL AND EXISTS (
  SELECT 1 FROM ticket_relations r
  WHERE r.relation_type = 'child_of' AND r.ticket_id = tickets.id
);

DELETE FROM ticket_relations WHERE relation_type IN ('parent_of', 'child_of');
-- 'client' joined the role lists after this schema shipped. Postgres can swap a
-- CHECK constraint in place, but the constraint has to be found by what it says
-- rather than by name, because an inline CHECK is named by Postgres itself.
DO $$
DECLARE
  target text;
  old_name text;
BEGIN
  FOREACH target IN ARRAY ARRAY['users', 'employees'] LOOP
    FOR old_name IN
      SELECT con.conname
      FROM pg_constraint con
      JOIN pg_class cl ON cl.oid = con.conrelid
      JOIN pg_namespace ns ON ns.oid = cl.relnamespace
      WHERE cl.relname = target
        AND ns.nspname = current_schema()
        AND con.contype = 'c'
        AND pg_get_constraintdef(con.oid) LIKE '%role%'
        AND pg_get_constraintdef(con.oid) NOT LIKE '%client%'
    LOOP
      EXECUTE format('ALTER TABLE %I DROP CONSTRAINT %I', target, old_name);
    END LOOP;

    IF NOT EXISTS (
      SELECT 1 FROM pg_constraint con
      JOIN pg_class cl ON cl.oid = con.conrelid
      JOIN pg_namespace ns ON ns.oid = cl.relnamespace
      WHERE cl.relname = target
        AND ns.nspname = current_schema()
        AND con.contype = 'c'
        AND pg_get_constraintdef(con.oid) LIKE '%role%'
    ) THEN
      EXECUTE format(
        'ALTER TABLE %I ADD CONSTRAINT %I CHECK (role IN (%L, %L, %L))',
        target, target || '_role_check', 'admin', 'developer', 'client'
      );
    END IF;
  END LOOP;
END $$;
